experiment:
  id: patchtst_etth1_336_96_baseline
  seed: 2026

model:
  name: PatchTST
  seq_len: 336
  pred_len: 96
  label_len: 48
  d_model: 64
  d_ff: 128
  n_heads: 4
  e_layers: 1

data:
  name: ETTh1
  features: M
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 16
  train_epochs: 1
  patience: 1
  learning_rate: 0.0001
